#!/bin/bash

logfile='/var/log/backups'
dbbakfilepath='/Storage/nextcloud-backup/nextcloud_db.bak'

configpath='/var/www/nextcloud/config/config.php'
configbakpath='/Storage/nextcloud-backup/config.php'

echo "$(date +%y-%m-%d-%H-%M) - Back up Nextcloud DB" | tee -a $logfile
sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --on

if [ $? -ne 0 ]; then
    echo "$(date +%y-%m-%d-%H-%M) - Failed to put Nextcloud in Maintenance Mode" | tee -a $logfile
    exit 1
fi

install -C -m 700 -o root -g root $configpath $configbakpath

mysqldump --single-transaction nextcloud > $dbbakfilepath

if [ $? -ne 0 ]; then
    echo "$(date +%y-%m-%d-%H-%M) - Failed to dump Nextcloud DB" | tee -a $logfile
    exit 1
fi

chmod 600 $dbbakfilepath

sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off

if [ $? -ne 0 ]; then
    echo "$(date +%y-%m-%d-%H-%M) - Failed to take Nextcloud out of Maintenance Mode" | tee -a $logfile
    exit 1
fi
