#!/bin/bash

logfile='/var/log/backups'
dbbakfilepath='/Storage/nextcloud-backup/nextcloud_db.bak'

configpath='/opt/nextcloud/nextcloud_data/config/config.php'
configbakpath='/Storage/nextcloud-backup/config.php'

echo "$(date +%y-%m-%d-%H-%M) - Back up Nextcloud DB" | tee -a $logfile
docker exec -u www-data nextcloud sh -c "php occ maintenance:mode --on"

if [ $? -ne 0 ]; then
    echo "$(date +%y-%m-%d-%H-%M) - Failed to put Nextcloud in Maintenance Mode" | tee -a $logfile
    exit 1
fi

install -C -m 700 -o root -g root $configpath $configbakpath

docker exec nextcloud_db_1 sh -c 'exec mysqldump --single-transaction nextcloud -p${MYSQL_ROOT_PASSWORD}' > $dbbakfilepath

if [ $? -ne 0 ]; then
    echo "$(date +%y-%m-%d-%H-%M) - Failed to dump Nextcloud DB" | tee -a $logfile
    exit 1
fi

chmod 600 $dbbakfilepath

docker exec -u www-data nextcloud sh -c "php occ maintenance:mode --off"

if [ $? -ne 0 ]; then
    echo "$(date +%y-%m-%d-%H-%M) - Failed to take Nextcloud out of Maintenance Mode" | tee -a $logfile
    exit 1
fi
