version: '3'

services:
    ansible-test:
        build: 
            context: ansible-test
            dockerfile: systemd.Dockerfile
        privileged: false
        tmpfs:
        - /run
        - /run/lock
        - /tmp
        volumes:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
        cap_add:
        - SYS_ADMIN
        networks:
            default:
                ipv4_address: 192.168.120.2
    
networks:
    default:
        ipam:
            driver: default
            config:
              - subnet: "192.168.120.0/24"
