---
## Run wich ansible-playbook -i test-hosts svard.me.yml
- hosts: all
  become: true
  tasks:
    - name: Update apt-cache
      apt: update_cache=yes
    - name: Install Packages
      apt:
        name: ["vim", "git"]
        state: latest
