version: "3"
services:
  grafana:
    image: zappka/phmeter
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: <password>
      GF_SERVER_ROOT_URL: http://phmeter.standersson.se
      MOSQ_PHMETER_PASS: <password>
      MOSQ_USER_PASS: <password>
      GF_DASHBOARDS_JSON_ENABLED: 'false'
      GF_SMTP_ENABLED: 'true'
      GF_SMTP_FROM_ADDRESS: phmeter@standersson.se
      GF_SMTP_FROM_NAME: PH-Meter
      GF_SMTP_HOST: 192.168.1.100:25
    ports:
      - 3000:3000
      - 1883:1883
    networks:
      - grafana-net
    volumes:
      - /opt/grafana/influxdb:/var/lib/influxdb
      - /opt/grafana/grafana:/var/lib/grafana

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - 2003:2003
    networks:
      - grafana-net

networks:
  grafana-net:

volumes:
  phdata:
  gfdata:
